### ISSUE TITLE
Unable to connect to Aurora

### ISSUE THREAD

**Issue by cajund** [flyway/flyway-docker#55] opened 2021-07-18 00:53 UTC
Hi Folks:

On an EC2 instance trying to migrate an Aurora RDS instance with the latest (7.11.2) container. I can connect with a mysql client, but can't connect using Flyway - so not a networking issue. Here's the error:

```
sudo docker run --rm -e FLYWAY_USER=user -e FLYWAY_PASSWORD=password -v $(pwd)/sql:/flyway/sql flyway/flyway:7.11.2 -url=jdbc:mysql://cluster-prod.cluster-chz6vzrkupce.us-east-2.rds.amazonaws.com:3306/dbname info
ERROR:
Unable to obtain connection from database (jdbc:mysql://cluster-prod.cluster-chz6vzrkupce.us-east-2.rds.amazonaws.com:3306/dbname) for user 'user': Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
```

Thanks in advance for any help.

**Comment by DoodleBobBuffPants** [comment] 2021-07-19 08:16
This looks like a duplicate of https://github.com/flyway/flyway-docker/issues/50, and see that for a workaround

**Closed as completed by DoodleBobBuffPants** 2021-07-19 08:16 UTC
