### ISSUE TITLE
support apple silicon

### ISSUE THREAD

**Issue by chauchakching** [flyway/flyway-docker#60] opened 2021-12-02 10:06 UTC
When the `amd64` platform image is used for running flyway, no log at all from the docker container.

So I tried to build the flyway image locally. After changing the `Dockerfile` base image to use latest version of `eclipse-temurin`, and build it with platform flag `linux/arm64`, the image works.

**Comment by DoodleBobBuffPants** [comment] 2021-12-02 10:08
Closing as duplicate of https://github.com/flyway/flyway-docker/issues/37

**Closed as completed by DoodleBobBuffPants** 2021-12-02 10:08 UTC

**Comment by okanji** [comment] 2022-01-19 18:33
@chauchakching, could you please share your Dockerfile with these changes?
